name: Deploy to Github Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.  s
            contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                repository: 's110b/vip'
                ref: 'master'  # 要检出的分支名
                token: ${{ secrets.GITHUB_TOKEN }}  # 或者你自己的PAT



